Develop
mate-academy/react_list-of-goods pull request #1049
Opened 2022-08-10 21:28 UTC by blcts

[DEMO LINK](https://blcts.github.io/react_list-of-goods/)

2022-08-11 07:20 UTC, katerinahradinarova approved these changes
well done:)

2022-08-11 08:01 UTC, ivan-kadykalo requested changes

2022-08-11 08:01 UTC, ivan-kadykalo commented on src/App.tsx
> +    });
Your sort will start every time and will check each element and do nothing
```suggestion
    switch (sortType) {
      case SortType.ALPABET:
        return visibleGoods.sort((a, b) => a.localeCompare(b));
      case SortType.LENGTH:
        return visibleGoods.sort((a, b) => a.length - b.length);
      case SortType.NONE:
      default:
        break;
    }
```

2022-08-15 09:14 UTC, VETALEK approved these changes
🚀

2023-04-19 13:38 UTC, closed without merging