implement list
mate-academy/react_list-of-goods pull request #1081
Opened 2022-09-07 11:55 UTC by tiserett

[DEMO LINK](https://tiserett.github.io/react_list-of-goods/)

2022-09-07 16:52 UTC, Dmytro-Matsehora requested changes

2022-09-07 16:52 UTC, Dmytro-Matsehora commented on src/App.tsx
> +        return 0;
this case is unnecessary here because it duplicates the `default` case

2022-09-07 17:00 UTC, Dmytro-Matsehora approved these changes
well done 🚀

2022-09-08 10:04 UTC, danylo-onishchuk approved these changes

2024-03-09 11:07 UTC, closed without merging