solution was added
mate-academy/react_list-of-goods pull request #1200
Opened 2022-10-20 15:36 UTC by Maksym845

- [DEMO LINK](https://Maksym845.github.io/react_list-of-goods/)

2022-10-23 16:01 UTC, Yeliseiev approved these changes
Nice!

2022-10-26 13:05 UTC, Andr1yK requested changes

2022-10-26 13:05 UTC, Andr1yK commented on src/App.tsx
> +  }
You have a predetermined number of options, so use switch case

2022-10-26 13:05 UTC, Andr1yK commented on src/App.tsx
> +                this.setSortType(SortType.NONE);
move to a separate function

2023-04-28 17:26 UTC, closed without merging