complete
mate-academy/react_list-of-goods pull request #1230
Opened 2022-10-26 10:22 UTC by barsuchellos

[DEMO LINK](https://barsuchellos.github.io/react_list-of-goods/)

2022-10-26 17:22 UTC, Andrew-Skoryk approved these changes
LGTM!

2022-10-27 08:29 UTC, Denchepornyuk requested changes

2022-10-27 08:29 UTC, Denchepornyuk commented on src/App.tsx
>    console.log(sortType, isReversed);
remove console.log from code

2022-10-27 08:29 UTC, Denchepornyuk commented on src/App.tsx
> +  };
you can create one function for that and pass SortType in the argument

2022-10-27 08:29 UTC, Denchepornyuk commented on src/App.tsx
> +          ))}
create a separate component for the goods list

2024-10-18 08:49 UTC, closed without merging