solution
mate-academy/react_list-of-goods pull request #138
Opened 2020-03-19 13:17 UTC by AnnieMarkina

https://anniemarkina.github.io/react_list-of-goods/

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +    state = { list: this.props.goodsList };
лучше делать переносы сразу, если потом захочешь еще что-то добавить
```suggestion
    state = {
      list: this.props.goodsList,
    };
```

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +    sortAlphb = () => {
пиши слова полностью

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +    reverseClick = () => {
```suggestion
    handleReverse = () => {
```
`handleSortLength`
`handleSortAlphabet`
исправь названия, придерживайся такого стиля

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +    reset = () => {
```suggestion
    handleReset = () => {
```

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +      // eslint-disable-next-line react/no-access-state-in-setstate
удали отключение, исправь ошибку

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +        Reverse
что с отступом?

2020-03-19 15:16 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +          <select onChange={event => this.selectNum(event.target.value)}>
```suggestion
          <select onChange={event => this.handleSelectChange(event.target.value)}>
```

2020-03-19 15:20 UTC, danheim commented on src/Components/ButtonsList/ButtonsList.js
> +            {this.state.list.map((item, index) => (
деструктурируй

2020-03-23 14:50 UTC, irenhh requested changes
комменты касаются всего кода, а не только того конкретного места, где они написаны

2020-03-23 14:50 UTC, irenhh commented on src/Components/ButtonsList/ButtonsList.js
> +        Reverse
отступы!!!

2020-03-23 14:50 UTC, irenhh commented on src/Components/ButtonsList/ButtonsList.js
> +              // eslint-disable-next-line react/no-array-index-key
убери это

2020-03-23 14:50 UTC, irenhh commented on src/Components/ButtonsList/ButtonsList.js
> +    const goodsArray = this.state.list;
деструктурируй this.state, не нужно переписывать в другие переменные

2020-03-23 14:50 UTC, irenhh commented on src/Components/ButtonsList/ButtonsList.js
> +    const items = [...this.state.list].slice(0, goodIndex);
нет нужды делать копию, slice и так создает новый массив

2020-03-23 14:50 UTC, irenhh commented on src/Components/ButtonsList/ButtonsList.js
> +    this.setState(prevState => ({ list: items }));
prevState тут не нужен

2020-03-23 14:50 UTC, irenhh commented on src/Components/ButtonsList/ButtonsList.js
> +    list: this.props.goodsList,
не нужно передавать в стейт из пропсов, делай все манипуляции над списком в родительском компоненте

2020-03-23 14:50 UTC, irenhh commented on src/Components/StartButton/StartButton.js
> +        <>
не нужно

2020-03-23 14:50 UTC, irenhh commented on src/Components/StartButton/StartButton.js
> +            : <SortingSection />}
```
{condition ? (
  ...
) : (
  ...
)}
```

2025-11-16 19:53 UTC, closed without merging