solution
mate-academy/react_list-of-goods pull request #1445
Opened 2023-01-30 16:05 UTC by igor-kashchenko

[DEMO LINK](https://igor-kashchenko.github.io/react_list-of-goods/)

2023-02-01 15:23 UTC, Anastasiia-Khudych approved these changes
Good job!

2023-02-01 17:32 UTC, Anna-Tkachenko requested changes

2023-02-01 17:32 UTC, Anna-Tkachenko commented on src/App.tsx
> +    = getReorderedGoods(goodsFromServer, { sortType, isReversed });
```suggestion
    const visibleGoods = getReorderedGoods(
      goodsFromServer,
      { sortType, isReversed },
    );
```

2023-02-01 17:32 UTC, Anna-Tkachenko commented on src/App.tsx
> +          {(isReversed || sortType !== SortType.NONE)
create separate boolean variable before `return` statement and store there the result of this check
in this way your code will be clearer
don't combine several checks directly in `jsx`

2023-02-02 15:29 UTC, Anna-Tkachenko approved these changes
⭐️

2024-11-08 14:13 UTC, closed without merging