Solution
mate-academy/react_list-of-goods pull request #1538
Opened 2023-03-09 14:47 UTC by stanislavcodes

[DEMO LINK](https://stanislavcodes.github.io/react_list-of-goods/)

2023-03-10 16:12 UTC, lilia-obushenko approved these changes
GJ!

2023-03-13 15:32 UTC, illiarerun requested changes

2023-03-13 15:32 UTC, illiarerun commented on src/App.tsx
> +              { 'is-light': isReversed === false },
it's a boolean value, you don't need a comparison
```suggestion
              { 'is-light': isReversed },
```

2023-03-13 15:32 UTC, illiarerun commented on src/App.tsx
> +            (isReversed || sortType !== SortType.NONE) && (
let's create a variable for this check

2023-03-13 15:32 UTC, illiarerun commented on src/App.tsx
>          </ul>
let's create component, smth like GoodsList

2023-03-14 12:38 UTC, illiarerun approved these changes

2026-07-06 09:21 UTC, closed without merging