Develop react_list-of-goods
mate-academy/react_list-of-goods pull request #1568
Opened 2023-03-20 16:50 UTC by sergey-lipikhin

[DEMO LINK](https://sergey-lipikhin.github.io/react_list-of-goods/)

2023-03-21 13:44 UTC, Anton-Tretiak approved these changes
Well done!

2023-03-21 16:23 UTC, OleksiiBlezniuk requested changes

2023-03-21 16:23 UTC, OleksiiBlezniuk commented on src/App.tsx
> +      break;
Let's move switch/case inside sort method, why duplicating it?

2023-03-21 16:23 UTC, OleksiiBlezniuk commented on src/App.tsx
> +              )}
Let's create `resetSorting` method, that will set initial values to state

2023-03-22 08:37 UTC, sergii-nosachenko requested changes

2023-03-22 08:37 UTC, sergii-nosachenko commented on src/App.tsx
> +              )}
```suggestion
              onClick={this.resetSorting}
```

2023-03-22 08:37 UTC, sergii-nosachenko commented on src/App.tsx
>          </ul>
Can be a separate component

2023-03-22 10:45 UTC, sergii-nosachenko approved these changes
Good work 👍
Commented

2023-03-22 10:45 UTC, sergii-nosachenko commented on src/App.tsx
> +  resetSorting = () => {
```suggestion
  resetSorting() {
```

2023-03-22 10:45 UTC, sergii-nosachenko commented on src/components/GoodsList/GoodsList.tsx
> +  return (
Useless `return`

2024-03-20 11:21 UTC, closed without merging