Solution
mate-academy/react_list-of-goods pull request #244
Opened 2020-09-05 09:02 UTC by 1nsider21

- [DEMO LINK](https://1nsider21.github.io/react_list-of-goods/)
1-6

2020-09-06 11:39 UTC, YuriiRysyn approved these changes
Good job)

2020-09-07 08:10 UTC, irenhh requested changes

2020-09-07 08:10 UTC, irenhh commented on src/components/GoodList.jsx
> +            goods.reverse();
write to the state

2020-09-07 08:10 UTC, irenhh commented on src/components/GoodList.jsx
> +            goods.sort((a, b) => a.length - b.length);
you're mutating the state here hence the app doesn't understand it needs to rerender this

2020-09-07 11:01 UTC, irenhh approved these changes

2023-08-22 11:54 UTC, closed without merging