done
mate-academy/react_list-of-goods pull request #274
Opened 2020-10-26 10:46 UTC by aionova

[DEMO LINK](https://aionova.github.io/react_list-of-goods/)

2020-10-26 11:12 UTC, AndriiManyak approved these changes
👍

2020-10-26 12:00 UTC, Vladimir-Beliy requested changes

2020-10-26 12:00 UTC, Vladimir-Beliy commented on src/App.js
> +          : ''}
```suggestion
        {showStartButton && (
            <ListButton
              onClickFunc={this.startList}
              title="start"
            />
          )}
```

2020-10-26 12:00 UTC, Vladimir-Beliy commented on src/App.js
> +          ? (
тоже самое

2020-10-26 14:37 UTC, Vladimir-Beliy requested changes

2020-10-26 14:37 UTC, Vladimir-Beliy commented on src/App.js
> +    goods: [...preparedGoods],
тут не нужен новый массив

2020-10-26 14:37 UTC, Vladimir-Beliy commented on src/App.js
> +      goods: [...preparedGoods],
тут тоже можно без нового массива

2020-10-26 14:37 UTC, Vladimir-Beliy commented on src/App.js
> +      goods: [...preparedGoods].filter(
```suggestion
      goods: preparedGoods.filter(
```
что вернет filter?

2020-10-26 14:37 UTC, Vladimir-Beliy commented on src/App.js
> +          </div>
в отдельный компонент

2020-10-26 17:00 UTC, aionova commented on src/App.js
> +      goods: [...preparedGoods].filter(
новый массив) дошло)

2020-10-27 11:56 UTC, Vladimir-Beliy approved these changes

2020-10-27 11:56 UTC, Vladimir-Beliy commented on src/App.js
> +  }
Ты все классно сделал. Только последнии два свойства стейта и функции которые с ними работаю нужно перенести PageContent. Таким образом ты не прокидываешь их сверху лишний раз и разделяешь логику.

2023-09-27 08:13 UTC, closed without merging