solution
mate-academy/react_list-of-goods pull request #286
Opened 2020-10-28 16:31 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/react_list-of-goods/)

2020-10-29 07:58 UTC, Suessophie approved these changes
Good)

2020-10-29 08:25 UTC, Vladimir-Beliy requested changes

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/App.js
> +  }
callback, а в стейтете boolean?
тебе не кажется это странным?

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/App.js
> +  }
callback.toString() <== это не понятно

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/App.js
> +  }
тут selectValue: '1', а в initialState selectValue: ''

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/App.js
> +            <GoodList
используй тернарный оператор

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/components/GoodsList/GoodList.jsx
> +  }) => (
```suggestion
export const GoodList = React.memo(({
    goodsList,
    goodsFromServer,
    selectValue,
    reverse,
    alphabeticalSort,
    lengthSort,
    reset,
    select,
 }) => (
```

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/components/GoodsList/GoodList.jsx
> +        })}
не понимаю как связано количество опций с количеством элементов

2020-10-29 08:25 UTC, Vladimir-Beliy commented on src/App.js
> +              select={this.select}
засунь те методы которые не нужны в этом компоненте в компонент GoodList

2020-10-29 10:17 UTC, andlap24 commented on src/App.js
> +  }
да, имя аргумента не то

2020-10-29 10:36 UTC, andlap24 commented on src/components/GoodsList/GoodList.jsx
> +        })}
именно в этом случае все ок, но я не подумал, что если кол-во элементов будет больше, а опций должно быть только 10. Поправлю

2020-10-29 15:10 UTC, mriynyk requested changes

2020-10-29 15:10 UTC, Vladimir-Beliy commented on src/App.js
> +        }
```suggestion
        {listVisibility ? (
            <GoodList
              goodsList={goodsFromServer}
              goodsFromServer={goodsFromServer}
            />
          ) : (
            <StartButton
              listVisibility={listVisibility}
              enter={this.enter}
            />
         )}
```

2020-10-29 15:10 UTC, Vladimir-Beliy commented on src/components/GoodsList/GoodList.jsx
> +        </select>
отдельный компонент

2020-10-29 15:10 UTC, Vladimir-Beliy commented on src/components/GoodsList/GoodList.jsx
> +        </ul>
отдельный компонент

2020-10-29 15:10 UTC, Vladimir-Beliy commented on src/components/SortButton/SortButton.jsx
> +    </Button>
целая куча кнопок которые отличаются только именем и onClick
+ пускай все кнопки будут в одном компоненте с кнопками

2020-10-30 09:27 UTC, Vladimir-Beliy approved these changes

2026-02-15 11:54 UTC, closed without merging