Solution
mate-academy/react_list-of-goods pull request #376
Opened 2021-03-11 18:32 UTC by b0hdan1

[DEMO LINK](https://<your_account>.github.io/react_list-of-goods/)

2021-03-12 11:19 UTC, vpolets commented
![Uploading image.png…]()

2021-03-12 11:22 UTC, vpolets requested changes

2021-03-12 11:22 UTC, vpolets commented on src/App.js
> +        .filter(good => good.length >= target.value),
навіщо копія? filter немутуючий метод

2021-03-12 11:22 UTC, vpolets commented on src/App.js
> +    }));
```suggestion
    this.setState(state => ({
      hiddenButtons: !state.hiddenButtons,
      hiddenStart: !state.hiddenStart,
    }));
```

2021-03-12 11:22 UTC, vpolets commented on src/components/GoodsList.js
> +          hidden={hiddenStart}
використовуй conditionalRendering замість того, щоб все в DOM запихати, а потім ховати

2021-03-12 11:22 UTC, vpolets commented on src/App.js
> +    }));
достатньо всього однієї змінної started

2021-03-15 14:35 UTC, vkryvytskyy approved these changes

2021-03-15 14:36 UTC, vkryvytskyy approved these changes

2024-04-25 17:16 UTC, closed without merging