created list of goods
mate-academy/react_list-of-goods pull request #395
Opened 2021-03-23 19:14 UTC by AnnaHarshyna

[DEMO LINK](https://AnnaHarshyna.github.io/react_list-of-goods/)

2021-03-23 19:22 UTC, SofiiaAsieieva approved these changes
Good job:fire:

2021-03-24 08:23 UTC, solaryasha requested changes

2021-03-24 08:23 UTC, solaryasha commented on src/App.js
> +          <Buttons
В однині, це ж компонент Кнопка

2021-03-24 08:23 UTC, solaryasha commented on src/App.js
> +            method={this.showListHandler}
```suggestion
            onClick={this.showListHandler}
```

2021-03-24 10:41 UTC, solaryasha approved these changes

2023-08-07 20:05 UTC, closed without merging