solved
mate-academy/react_list-of-goods pull request #411
Opened 2021-04-07 13:19 UTC by JohnCrownHC

[DEMO LINK](https://JohnCrownHC.github.io/react_list-of-goods/)

2021-04-07 13:54 UTC, RuslanKalyniak commented
гугл плеча за тобою)

2021-04-08 10:22 UTC, Denchepornyuk requested changes
good job 👍

2021-04-08 10:22 UTC, Denchepornyuk commented on src/components/List/List.jsx
> +      goods: prev.goods.reverse(),
reverse метод який мутує масив тому краще перед цим методом зробити копію масиву

2021-04-08 10:22 UTC, Denchepornyuk commented on src/components/List/List.jsx
> +    }));
sort також мутує масив тому краще зробити копію

2021-04-08 10:22 UTC, Denchepornyuk commented on src/components/List/List.jsx
> +            >
```suggestion
            <ListGroupItem key={uuidv4()}>
```

2021-04-09 08:37 UTC, Denchepornyuk approved these changes

2024-04-18 12:33 UTC, closed without merging