solution
mate-academy/react_list-of-goods pull request #444
Opened 2021-05-25 13:51 UTC by Andriykooo

[DEMO LINK](https://Andriykooo.github.io/react_list-of-goods/)

2021-05-26 07:39 UTC, illisogori requested changes
В основном компоненте должна быть только кнопка start и компонент GoodsList.
Сортировка должна быть в компоненте GoodsList.

2021-05-26 07:39 UTC, illisogori commented on src/App.js
> +      goods: [...state.goods].reverse(),
```suggestion
      goods: [...state.goods] 
```
Лучше один раз сделать копию в переменную.

2021-05-27 10:38 UTC, Andriykooo commented on src/App.js
> +      goods: [...state.goods].reverse(),
Мені ж всерівно потрібно буде кожен раз робити копію при внесенні змін в state, я просто не розумію навіщо копію тут переносити в окрему перемінну. Якщо б я міняв масив в самому рендері, то, напевно так, було б логічно використати перемінну

2021-05-27 11:05 UTC, illisogori approved these changes
Good job.

2021-05-27 11:11 UTC, illisogori commented on src/App.js
> +      goods: [...state.goods].reverse(),
можно не хранить массив в state, хранить в state только то что надо делать  с массивом isReversed,
    sortBy. В рендере GoodsList уже преобразовывать.

2021-05-27 11:22 UTC, illisogori commented on src/App.js
> +      goods: [...state.goods].reverse(),
Ты прав. Можно не хранить goods в state, хранить только то как его менять isReversed, sortBy, и в рендере делать одну копию.

2021-05-27 13:40 UTC, mykola-yarchuk requested changes

2021-05-27 13:40 UTC, mykola-yarchuk commented on src/components/GoodsList.jsx
> +    goods: this.props.goodsList,
https://stackoverflow.com/questions/40063468/react-component-initialize-state-from-props
don't use props in the state

2021-05-27 16:02 UTC, mykola-yarchuk approved these changes

2022-09-21 14:43 UTC, closed without merging