solution
mate-academy/react_list-of-goods pull request #469
Opened 2021-05-26 10:52 UTC by BilliZane

[DEMO LINK](https://BilliZane.github.io/react_list-of-goods/)

2021-05-26 10:59 UTC, stas-dukach approved these changes
Otlichno!

2021-05-26 14:48 UTC, varseniuk requested changes
The logic is correct, but you are mutating the state. Create a copy of an array and make all changes with it

2021-05-26 14:48 UTC, varseniuk commented on src/ListOFGoods.js
> +      goods: state.goods.reverse(),
Don't mutate the state. Create a copy of an array and make all sortings with it

2021-05-27 07:13 UTC, varseniuk requested changes
You are still mutating the state

2021-05-27 07:13 UTC, varseniuk commented on src/GoodsList.jsx
> +  }
```suggestion
  reverse = () => {
    this.setState(state => ({
      goodsList: [...state.goodsList].reverse(),
    }));
  }
```
You're still mutating the state. 'reverse` and `sort` are mutating methods. Create a copy and make all operations with it

2021-05-27 07:13 UTC, varseniuk commented on src/GoodsList.jsx
> +      goodsList: state.goodsList.sort(),
```suggestion
      goodsList: [...state.goodsList].sort(),
```

2021-05-27 07:13 UTC, varseniuk commented on src/GoodsList.jsx
> +      goodsList: state.goodsList.sort((a, b) => a.length - b.length),
```suggestion
      goodsList: [...state.goodsList].sort((a, b) => a.length - b.length),
```

2021-05-27 09:58 UTC, varseniuk approved these changes

2023-09-26 15:14 UTC, closed without merging