Task was solved
mate-academy/react_list-of-goods pull request #652
Opened 2021-11-11 14:24 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_list-of-goods/)

2021-11-15 08:44 UTC, olena1994 approved these changes

2021-11-15 11:27 UTC, VinnieJ-2k20 requested changes
Solution looks good, but let's stick to the task.
- After clicking the `Start` button it must be hidden
> After clicking the button show a `GoodsList` (`ul` > `li`) with the given goods and hide the button
- All controls (buttons) should be in the App, GoodsList should only render already prepared list of goods.

2021-11-16 10:21 UTC, VinnieJ-2k20 approved these changes
Good job 👍 
Check the comments.

2021-11-16 10:21 UTC, VinnieJ-2k20 commented on src/App.tsx
> +      isVisible: prevState.isVisible,
No need to rewrite it if it doesn't change.

2021-11-16 10:21 UTC, VinnieJ-2k20 commented on src/App.tsx
> +      isVisible: prevState.isVisible,
Same here.

2021-11-16 10:21 UTC, VinnieJ-2k20 commented on src/App.tsx
> +      isVisible: prevState.isVisible,
And here.

2025-01-20 16:29 UTC, closed without merging