Develop
mate-academy/react_list-of-goods pull request #729
Opened 2022-01-22 22:59 UTC by andrii-koptiev

[DEMO LINK](https://andrii-koptiev.github.io/react_list-of-goods/)

2022-01-24 10:11 UTC, MaksimusCRS approved these changes
Крутой дизайн)

2022-01-24 10:11 UTC, MaksimusCRS commented on src/App.tsx
> +                <MenuItem value={10}>10</MenuItem>
Думаю, если бы было больше таких значений(100+), то это бы не было лучшим решением, надо бы на будущее придумать какой-то цикл)

2022-01-24 10:11 UTC, MaksimusCRS commented on src/App.tsx
> +    }
Лучше бы это всё вынести в отдельную функцию, а то не красиво получается

2022-01-24 10:19 UTC, andrii-koptiev commented on src/App.tsx
> +                <MenuItem value={10}>10</MenuItem>
согласен. но тут я подумал что это не нужно, так как у нас четко указано 10 символов.

2022-01-24 10:20 UTC, andrii-koptiev commented on src/App.tsx
> +    }
так это и есть отдельные функции, просто пишем их в рендере, что бы логику реализовать

2022-01-26 09:46 UTC, danheim requested changes

2022-01-26 09:46 UTC, danheim commented on src/App.tsx
> +  sortBy: string;
create enum

2022-01-26 09:46 UTC, danheim commented on src/App.tsx
> +    goodLength: '1',
length? it should be number, not a string

2022-01-26 09:46 UTC, danheim commented on src/App.tsx
> +    this.setState({ goodLength: '1' });
зачем тебе три разных setState? напиши все в одном

2022-01-26 09:46 UTC, danheim commented on src/App.tsx
> +                <MenuItem value={1}>1</MenuItem>
нарендерь циклом forEach, погугли / придумай

2022-01-26 19:50 UTC, danheim approved these changes

2023-09-26 21:09 UTC, closed without merging