Develop
mate-academy/react_list-of-goods pull request #855
Opened 2022-05-10 19:27 UTC by ivan-kadykalo

[DEMO LINK](https://ivan-kadykalo.github.io/react_list-of-goods/)

2022-05-11 09:38 UTC, lem47 approved these changes
Все чудово, молодець!

2022-05-12 09:17 UTC, Andr1yK requested changes
Хороша робота, та є що покращити))

2022-05-12 09:17 UTC, Andr1yK commented on src/App.scss
> +.goods {
Окремий блок - окремий файл

2022-05-12 09:17 UTC, Andr1yK commented on src/App.tsx
> +        <button
замість display: none краще юзай умовний рендер, тому що ти його тільки приховуєш, але всеодно тратиш ресурси на рендер)

2022-05-12 09:17 UTC, Andr1yK commented on src/components/List.tsx
> +  sortBy: string;
Використай enum)

2022-05-12 09:17 UTC, Andr1yK commented on src/components/List.tsx
> +              `goods__button ${sortBy === 'length' && 'goods__button--active'}`
можеш використати бібліотеку [classnames](https://www.npmjs.com/package/classnames)

2022-05-12 09:17 UTC, Andr1yK commented on src/components/List.tsx
> +            <option value="10">{'Word length >= 10'}</option>
А чому б рендерити це з масиву?)
Можеш використати [map](https://developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/map) i [from](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

2022-05-12 10:52 UTC, ivan-kadykalo commented on src/components/List.tsx
> +              `goods__button ${sortBy === 'length' && 'goods__button--active'}`
Змінив на classnames однак на мою думку без використання цієї бібліотеки якось простіше та менше коду (як мінімум при такій кількості класів як є зараз)

2022-05-13 08:10 UTC, Andr1yK commented on src/components/List.tsx
> +              `goods__button ${sortBy === 'length' && 'goods__button--active'}`
Погоджусь, коли так мало класів, то код стає більший, тому це була тільки рекомендація)

2022-05-13 08:12 UTC, Andr1yK approved these changes

2022-05-13 08:12 UTC, Andr1yK commented on src/components/List/List.tsx
> +import classNames from 'classnames';
щоб було менше коду можеш імпортувати `cn` ))

2022-05-13 08:12 UTC, Andr1yK commented on src/components/List/List.tsx
> +      case 'alphabet':
Краще юзати enum

2022-05-13 08:57 UTC, ivan-kadykalo commented on src/components/List/List.tsx
> +      case 'alphabet':
Switch був згорнутий і я цей кусок пропустив)) Вже поміняв

2023-08-08 17:39 UTC, closed without merging