Solution
mate-academy/react_list-of-goods pull request #869
Opened 2022-05-12 06:22 UTC by YegorKochetkov

[DEMO LINK](https://YegorKochetkov.github.io/react_list-of-goods/)

2022-05-12 07:10 UTC, Vakolyyk approved these changes
All good!

2022-05-12 09:47 UTC, Andr1yK requested changes
Те що ти використовуєш uuid це круто, тільки ці id потрібно генерувати до рендеру, щоб на кожному наступному рендері вони не змінювались)

2022-05-12 09:47 UTC, Andr1yK commented on src/components/ListOfGoods/ListOfGoods.tsx
> +          key={uuidv4()}
тут юзати uuid не потрібно, тому що при кожному рендері в тебе буде інший idшний і так навпаки заплутуєш реакт, якщо хочеш подробніше можеш зайти на QnA)

2022-05-12 09:47 UTC, Andr1yK commented on src/components/SortableList/SortableList.tsx
> +                        key={uuidv4()}
не можна генерувати ключі підчас рендеру, тому що на кожному рендері вони в тебе будуть різні)

2022-05-12 16:08 UTC, YegorKochetkov commented on src/components/ListOfGoods/ListOfGoods.tsx
> +          key={uuidv4()}
спасибо, вроде понял. не подумал про это. переделал по простому)
можно не делать подготовленный список goods с id?)

2022-05-13 08:15 UTC, Andr1yK commented on src/components/ListOfGoods/ListOfGoods.tsx
> +          key={uuidv4()}
Тут ти можеш просто goods передавати в key))

2022-05-13 08:16 UTC, Andr1yK approved these changes

2025-04-25 20:14 UTC, closed without merging