React list of goods
mate-academy/react_list-of-goods pull request #945
Opened 2022-07-08 11:23 UTC by vsupruniuk

[DEMO LINK](https://vsupruniuk.github.io/react_list-of-goods/)

2022-07-12 10:32 UTC, stanislav-topikha requested changes
Overall good 👍🏻 

but read the comments below ⏬ 

and consider making this button's separate, not in a group
![image](https://user-images.githubusercontent.com/99331793/178470812-1b1492e9-b11a-4a8f-a21b-7d6c235cfa56.png)

2022-07-12 10:32 UTC, stanislav-topikha commented on src/App.tsx
> +                <option value="10">10</option>
maybe loop can handle it?)

2022-07-12 10:32 UTC, stanislav-topikha commented on src/App.tsx
> +  };
use correct naming for event handlers: 
https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2022-07-12 11:07 UTC, stanislav-topikha approved these changes

2022-07-13 07:21 UTC, Olexandr6 requested changes

2022-07-13 07:21 UTC, Olexandr6 commented on src/App.tsx
> +    }
This logic shouldn't be here. Method render should be as clear as possible.
Let's move this logic to a separate method

2022-07-13 14:12 UTC, Olexandr6 approved these changes

2024-01-28 12:18 UTC, closed without merging