Solution
mate-academy/react_list-of-goods pull request #947
Opened 2022-07-08 18:35 UTC by mira1zu

- [DEMO LINK](https://mira1zu.github.io/react_list-of-goods/)

2022-07-12 15:21 UTC, AndriiNychaiuk approved these changes
👍

2022-07-13 07:32 UTC, Olexandr6 requested changes
Good solution, let's work on impovements

2022-07-13 07:32 UTC, Olexandr6 commented on src/App.tsx
> +  onStartButtonClick = () => {
This naming is suitable for a component props, not for handler functions

Read more: https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2022-07-13 07:32 UTC, Olexandr6 commented on src/App.tsx
> +    }
This logic shouldn't be here. Method `render` should be as clear as possible.
Let's move this logic to a separate method

2022-07-13 07:32 UTC, Olexandr6 commented on src/App.tsx
> +                        // eslint-disable-next-line react/no-array-index-key
🥲

2022-07-13 07:32 UTC, Olexandr6 commented on src/App.tsx
> +                          minLength: +target.value,
```suggestion
                          minLength: Number(target.value),
```

2022-07-14 16:10 UTC, Olexandr6 approved these changes

2022-12-08 22:09 UTC, closed without merging