Solution
mate-academy/react_list-of-goods pull request #979
Opened 2022-07-14 22:01 UTC by khrystyna-sabat

[DEMO LINK](https://khrystyna-sabat.github.io/react_list-of-goods/)

2022-07-16 13:01 UTC, Bohdan-Pyschchyk approved these changes

2022-07-18 11:03 UTC, illiarerun requested changes

2022-07-18 11:03 UTC, illiarerun commented on src/App.tsx
> +  length,
Let's use ALLCAPS, cause it's mainly used for such constants values like this
```suggestion
  NONE,
  ALPABET,
  LENGTH,
```

2022-07-18 11:03 UTC, illiarerun commented on src/App.tsx
> +            }}
LEt's create a function handler for this action

2022-07-18 11:03 UTC, illiarerun commented on src/App.tsx
> +              }}
same here

2022-07-18 11:03 UTC, illiarerun commented on src/App.tsx
> +                }));
and also here

2022-07-18 11:03 UTC, illiarerun commented on src/App.tsx
> +              }}
here you can create a handler, smth like a `sortBy` function which will take a `sortType` param with `SortType` type, and just pass needed `SortType`

2022-07-18 11:03 UTC, illiarerun commented on src/App.tsx
> +              }}
and then use it here, also

2022-07-19 07:56 UTC, jstmpelowycz approved these changes

2022-07-19 07:56 UTC, jstmpelowycz commented on src/App.tsx
> +        && (
you'd rather use ternary here

2022-07-19 07:56 UTC, jstmpelowycz commented on src/App.tsx
> +  started = () => {
```suggestion
  show = () => {
```

2022-07-19 07:56 UTC, jstmpelowycz commented on src/App.tsx
> +  sortByAlphabetically = () => {
```suggestion
  sortAlphabetically = () => {
```

2022-11-21 15:42 UTC, closed without merging